### ISSUE TITLE
Missing bochsrc.txt

### ISSUE THREAD

**Issue by joshwatson** [googleprojectzero/bochspwn#3]
The documentation (page 8) says that a bochsrc.txt file should be found in the source archive, similar to the config.txt file. Additionally, the documentation provides an example config.txt; however, the bochsrc.txt file appears to be missing from the archive.

Can this file be provided? Thanks!

**Comment by j00ru** [comment]
Apologies for the inconvenience, but I'm afraid we can't locate the exact bochsrc.txt we referred to in the documentation back in 2013. However, a standard bochsrc file from a clean installation of Bochs should work just fine, with the only major tweak being setting the right path to the guest's hdd image in the host's file system.
