### ISSUE TITLE
Mingw doesn't compile protoc file as ELF

### ISSUE THREAD

**Issue by ghost** [googleprojectzero/bochspwn#4]
When I did configure with below commands:
`./configure --host=i686-w64-mingw32 --prefix=/usr/i686-w64-mingw32/
`
Then comment out the unittest_proto_middleman test from the src/Makefile file and run make command.
But I am getting below mentioned error:
```
libtool: link: i686-w64-mingw32-g++ -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG -pthread -o .libs/protoc.exe main.o  ./.libs/libprotobuf.dll.a ./.libs/libprotoc.dll.a /home/pwn/protobuf-2.5.0/src/.libs/libprotobuf.dll.a -pthread -L/usr/i686-w64-mingw32/lib
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/home/pwn/protobuf-2.5.0/src/.libs'
libtool:   error: Continuing, but uninstalled executables may not work.
libtool:   error: Could not determine the host path corresponding to
libtool:   error:   '/home/pwn/protobuf-2.5.0/src/.libs:/usr/i686-w64-mingw32/lib:/usr/i686-w64-mingw32/bin'
libtool:   error: Continuing, but uninstalled executables may not work.
make[3]: Leaving directory '/home/pwn/protobuf-2.5.0/src'
make[2]: Leaving directory '/home/pwn/protobuf-2.5.0/src'
make[1]: Leaving directory '/home/pwn/protobuf-2.5.0'
```
After that When I run make install and run protoc command.
I'm getting this error: 
`The program 'protoc' is currently not installed.
`It compiles only protoc.exe for Win platforms.

```
root@ubuntu:/home/pwn/protobuf-2.5.0# ls -la /usr/i686-w64-mingw32/bin/
libprotobuf-8.dll       libprotobuf-lite-8.dll  libprotoc-8.dll         protoc.exe

```

**Comment by j00ru** [comment]
Hi Emin,

It is necessary to compile and install Protocol Buffers both for the mingw cross-compiler (`./configure --host=i686-w64-mingw32 --prefix=/usr/i686-w64-mingw32/` or similar) and your local compiler toolchain (`./configure`). This is noted in the documentation:

> It may also make sense to follow the same above three steps with a vanilla ./configure
> command, so that the Linux protoc utility is installed in your system, enabling you to transform
> .proto definition files to actual .cc / .h files implementing the specified protocols.

The i686-w64-mingw32 part is necessary to install the libprotobuf libraries that can be later used by the cross-compiler to build `bochs.exe` for Windows. The local part is required to get the `protoc` tool that is locally used to convert the `.proto` file into a pair of `.cc`/`.h`.

I hope that helps,
Mateusz
