### ISSUE TITLE
update DOCUMENTATION.old.md

### ISSUE THREAD

**Issue by houjingyi233** [googleprojectzero/bochspwn#5]
"In the LIBS environment variable, choose dbghelp.lib for a 32-bit build and dbghelp.dll for a 64-bit build."
 
Maybe should be changed to:

"In the LIBS environment variable, choose 32bit dbghelp.lib or dbghelp.dll for a 32-bit build and 64bit dbghelp.lib or dbghelp.dll for a 64-bit build."

**Comment by j00ru** [comment]
I applied your suggestion in commit f8c238ae19cd22fdebb9ba5aa5ee034829b4512e.
